#!/bin/bash
#    Pure-bash irc client
#    Copyright (C) 2011 Sebastian Götte <s@jaseg.de>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


user="crlf"

function irccmd {
	echo -e "$1\r" >&3
}

function send_message {
	if [ -n "$2" ]; then
		irccmd "PRIVMSG $1 :$2"
	fi
}

function parse_command {
	if [[ "$1" =~ /join\ ([^ ]*) ]]; then
		chan=${BASH_REMATCH[1]}
		if [ -n "$chan" ]; then
			if [[ ! "$chan" =~ ^# ]]; then
				chan="#$chan"
			fi
			echo "Joining $chan..."
			irccmd "JOIN $chan"
		fi
		return 1
	fi
	return 0
}

function screen_print {
	echo "$@"
}

function exittrap {
	echo 'Exiting.'
	kill -9 $slavepid 2>/dev/null
	exec 3>&-
} 

#open the socket
exec 3<>"/dev/tcp/irc.telecomix.org/6667"
#login
irccmd "NICK $user"
irccmd "USER $user * * :$user"
#process user input
{
	while read -e line
	do	if [[ "$line" =~ ^/ ]]
		then parse_command "$line"
		else send_message $chan "$line"
		fi
	done<&1
}&
slavepid=$!
trap exittrap 0

{ #process server messages
	while read line
	do	#echo "DEBUG $line"
		if [[ "$line" =~ ^[^\ ]*\ [0-9]*\ (.*) ]]; then
			screen_print "${BASH_REMATCH[1]}"
		elif [[ "$line" =~ ^:([^\!]*)\![^:]*:(.*) ]]; then
			screen_print "<${BASH_REMATCH[1]}> ${BASH_REMATCH[2]}"
		fi
	done<&3
}
