#!/bin/bash
#This script has been written to mount and dismount an luks-encrypted hard drive. I needed it because back then on my ubuntu the hard drive would not properly survive a suspend, with the links in /dev/mapper being unreadable as well as undeletable. Although it is *not* the most elegant solution at the time it worked.
if [ $(id -u) -ne 0 ]; then
        echo "This script must run as root."
        sudo $0
        exit
fi
if [ "$1"="mount" -o "$1"="m" -o "$1"="open" ]
then	while umount /media/harddisk&>/dev/null
	do      true
	done
	for mapping in $(ls /dev/mapper|egrep 'harddisk+$')
	do      cryptsetup luksClose $mapping&>/dev/null
	done
	newmapping=$(ls /dev/mapper|egrep 'harddisk+$'|tail -n 1)a
	cryptsetup luksOpen /dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx $newmapping
	mount /dev/mapper/$newmapping /media/harddisk
else	if [ "$1"="unmount" -o "$2"="umount" -o "$2"="u" -o "$2"="close" ]
	then	while umount /media/harddisk&>/dev/null
	do      true
	done
	for mapping in $(ls /dev/mapper|egrep 'harddisk+$')
	do      cryptsetup luksClose $mapping&>/dev/null
	done
	else	echo 'Operation not found. Valid are e.g. "mount" and "umount"'
		exit 2
	fi
fi

