#!/bin/bash
#This script change the mac addresses of all network devices (at least of all with names beginning with either "eth" or "wlan"). The current macs are backed up to /tmp/. Note: A more permanent backup is not necessary since normal network devices reset their macs on each reboot.
if [ $(id -u) -ne 0 ]; then
	echo "This script must run as root."
	sudo $0
	exit
fi

DEVICES=$(ifconfig -a|grep -E "(eth)|(wlan)"|cut -d" " -f1|sort)
dte=$(date +%Y%m%d%H%M%S)

for dev in $DEVICES
do	ifconfig "$dev" down
	macchanger -s "$dev" | cut -d" " -f 3 > "/tmp/${dev}_mac_$dte"
	echo "Backed up MAC address of $dev to /tmp/${dev}_mac_$dte"
	macchanger -a "$dev"
	echo "Changed MAC address of $dev"
	ifconfig "$dev" up
done
