#!/bin/bash
#Script for testing wlan range (server)
trap 'echo -e "\033[0;39m"' 0

i=0

while true
do
	nc -l 12345 -w 3 2> /dev/null
	if [ $? -eq 0 ]
	then
		echo -e "\033[1;32m$i\tCONNECTED"
		date
		echo
#		head -n 2 gpsfifo_master >> coordlist_master &
#		play beep.wav 2> /dev/null
	else
		echo -e "\033[1;31m$i\tDISCONNECTED"
		date
		echo
#		head -n 2 gpsfifo_master >> coordlist_master &
#		play beep2.wav 2> /dev/null
	fi
	sleep 0.1s
	jobs
	let i=i+1
done

