#!/bin/bash

if [ $(id -u) -ne 0 ]; then
	echo "This script must run as root."
	sudo $0
	exit
fi

key=$(iwconfig 2> /dev/null | grep key | cut -d: -f2)
	function say(){
	for i in $(seq 1 ${#key})
	do	espeak -s 100 -v german $(echo $key|cut -c $i)
	done
}

say
while read
do	say
done
