#!/bin/bash
#Tells the current time in full german sentences

function short {
	s=$(date -d "+5 sec" $1)
	if [ ${s:0:1} = 0 ]; then
		echo ${s:1}
	else
		echo $s
	fi
}

function short2 {
	if [ $1 = 1 ]; then
		echo ein
	else
		echo $1
	fi
}

function short3 {
	if [ $1 = 15 ]; then
		echo viertel
	else
		echo $1
	fi
}

function rund {
	b=$1
	let b=b+2; let b=(b*5); let b=(b-b%25)/5
	echo $b
}

function tayme {
	h=$(short +%I)
	m=$(short +%M)
	s=$(short +%S)
	if [ $s -ge 30 ] ;then
		let m=m+1
	fi
	if [ $m -eq 60 ] ;then
		let h=h%12+1
	fi
	m=$(rund $m)
	if [ $m -lt 30 ] ;then
		if [ $m -eq 0 ] ;then
			echo um $h
		else
			if [ $m -eq 25 ] ;then
				let h=h%12+1
				echo 5 vor halb $h
			else
				echo $(short3 $m) nach $h
			fi
		fi
	else
		let h=h%12+1
		if [ $m -gt 35 ] ;then 
			let m=60-m
			if [ $m -eq 0 ] ;then
				echo um $h
			else
				echo $(short3 $m) vor $h
			fi
		else
			if [ $m -eq 35 ] ;then
				echo 5 nach halb $h
			else
				echo halb $h
			fi
		fi
	fi
}

s="   Es ist jetzt $(tayme ' Uhr ' ' und ' ' Sekunden')  "
echo $s
espeak -v german ".      $s" -a 500 -w ~/tmp.wav
play ~/tmp.wav -q
rm ~/tmp.wav
